services:
  - type: web
    name: doc-converter-backend
    runtime: python
    buildCommand: |
      cd backend
      ./build.sh
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_RUN_HOST
        value: 0.0.0.0
      - key: FLASK_DEBUG
        value: "0"
      - key: WKHTMLTOPDF_PATH
        value: /usr/bin/wkhtmltopdf
